services:
  database:
    image: mysql:8.0
    container_name: techrevamp-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: techrevamp
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build: ./TechRevamp-Backend
    container_name: techrevamp-backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://techrevamp-db:3306/techrevamp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

  frontend:
    build: ./TechRevamp-Frontend
    container_name: techrevamp-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
